Smoke test
SFDO-Tooling/MetaDeploy pull request #1814
Opened 2020-10-06 16:14 UTC by Br4nd0R

2020-10-13 14:26 UTC, davisagli requested changes

2020-10-13 14:26 UTC, davisagli commented on .github/workflows/smoke_test.yml
> +          pip install cumulusci
fwiw, the command can go on the same line without the pipe when there's a single command.

2020-10-13 14:26 UTC, davisagli commented on .github/workflows/smoke_test.yml
> +          $(which cci) org info enterprise
I'm pretty sure you can just call cci. The `$(which cci)` idiom was for when cci was being run by coverage.py which needed the full path.

2020-10-13 19:26 UTC, davisagli commented on .heroku/release.sh
> +echo "Done."
Also, this dispatch to github needs to be something that's off by default but can be turned on with a config var. We don't want other instances of MetaDeploy triggering our build (and their GITHUB_TOKEN probably doesn't have access to)

2020-10-13 19:50 UTC, Br4nd0R commented on .heroku/release.sh
> +echo "Done."
I'll start with a 5 minute delay before the robot tests start with.

2020-10-13 20:29 UTC, davisagli commented on .heroku/release.sh
> +echo "Done."
@Br4nd0R Still needs a way for us to enable it only for some deployments of metadeploy.

2020-10-14 19:08 UTC, davisagli approved these changes
Looking good!

2020-10-14 19:18 UTC, merged