Warn Checks Should Not Block Error Checks
SFDO-Tooling/MetaDeploy pull request #2232
Opened 2021-01-15 20:30 UTC by Br4nd0R

# Changes
* `PreflightFlowCallback.post_flow` now saves all results for a given step to the results of the PreflightResult or Job.

## Outstanding
* Figure out front-end logic for displaying pre-flight results when more than one is present. Should we only show one based on precedence (i.e. errors first, then warnings), or should we display all results at the same time.

2021-02-12 19:55 UTC, davisagli requested changes
Good work -- overall looks good, but I have questions about a few details

2021-02-12 19:55 UTC, davisagli commented on src/js/components/jobs/shareModal.tsx
> +        // of results for a given step
Looks like it's actually returning the first error

2021-02-12 19:55 UTC, davisagli commented on src/js/components/plans/detail.tsx
> +            steps.push(step);
Won't this add a step to the list multiple times if it has multiple non-HIDE results?

2021-02-12 19:55 UTC, davisagli commented on src/js/components/plans/detail.tsx
> +        }
This is overwriting these flags on each iteration over the results. Instead I think we want to _collect_ them. i.e. `hidden` should be true if any result was HIDE, `skipped` should be true if any result was SKIP, etc

2021-02-12 19:55 UTC, davisagli commented on src/js/components/plans/stepsTable/index.tsx
> +  };
I think you've changed the logic here in a way that doesn't make sense. The point was to find the first step that doesn't have any results yet. But this will find the first step that has results where one of the results doesn't have a status (is that even possible?) Probably worth QA to make sure that wherever this is used is getting the right step.

2021-02-12 19:55 UTC, davisagli commented on src/js/components/plans/stepsTable/index.tsx
> +  };
Since this is the main job, not the preflight, I think you can safely assume that there will be either 0 results or 1. So you could just check job.results[stepId][0].logs rather than looping

2021-02-12 19:55 UTC, davisagli commented on src/js/components/plans/stepsTable/installDataCell.tsx
> +        optional = result.status === RESULT_STATUS.OPTIONAL ? result : null;
Again, I think we want to collect values from multiple results here, not overwrite with the values based on the last result.

2021-02-12 19:55 UTC, davisagli commented on src/js/components/plans/stepsTable/requiredDataCell.tsx
> +      optional = result.status === RESULT_STATUS.OPTIONAL ? result : null;
Ditto

2021-02-12 19:55 UTC, davisagli commented on src/js/store/plans/reducer.ts
>  };
Maybe this type should be called PlanResults, since it's used for both Jobs and Preflights, and a single result might express a status other than error

2021-02-12 19:55 UTC, davisagli commented on test/js/components/plans/preflightResults.test.js
> +      // TODO: Only errors should be displayed
todo

2021-02-18 16:33 UTC, Br4nd0R commented on src/js/components/plans/stepsTable/index.tsx
> +  };
@davisagli - I agree something is off here, but isn't the original logic similar? The `if` check will be true when either:
(1) There are no results for the step yet (and `?.` will return undefined)
(2) There are results but a `status` is not present (i.e. the only "results" are the logs set by the `ResultSpoolLogger`.

If I make the function return `true` if there are no results for a step, then it looks like the "in progress" step is one ahead of where it should be. Put another way, the step that has logs currently being output is not shown as the "in progress" step. So I'm guessing this is why the function was originally checking for the presence of `status`, as it seems to be set by `JobFlowCallback.post_task()`.

2021-02-18 16:39 UTC, Br4nd0R commented on src/js/components/plans/stepsTable/index.tsx
> +  };
Ok I think I got it working :)

2021-02-18 17:09 UTC, Br4nd0R commented on src/js/components/plans/detail.tsx
> +        }
@davisagli - Do we know if it's safe to assume that there will ever only be one result with a "status" value? I'm trying to determine wether or not `hidden`, `skipped`, and `optional` need to be lists of results or if it will suffice to just use the first results found with a given status.

2021-02-18 21:32 UTC, davisagli commented on src/js/components/plans/detail.tsx
> +        }
@Br4nd0R A step with multiple preflight checks can have multiple results, each with its own status. e.g. [{"status": "skip", "message": "Skipped because X"}, {"status": "hide"}]. The goal here is to end up with a boolean for hidden, skipped, and optional indicating whether any of the results had that status.

So I think something like this would do it, no loop needed:
```
const results = preflight?.results?.[id] || [];
const hidden = results.some(result => result.status === RESULT_STATUS.HIDE);
const skipped = results.some(result => result.status === RESULT_STATUS.SKIP);
const optional = results.some(result => result.status === RESULT_STATUS.OPTIONAL);
```

2021-02-18 21:34 UTC, davisagli commented on src/js/components/plans/stepsTable/index.tsx
> +  };
Makes sense. I forgot about the logs when I wrote this comment.

2021-02-18 21:36 UTC, davisagli commented
@Br4nd0R there are a few Python tests for ResultSpoolLogger that need to be adjusted

2021-02-18 23:10 UTC, Br4nd0R commented on src/js/components/plans/detail.tsx
> +        }
`installDataCell.tsx` will need to have an actual `result` object captured. It later references `skipped?.label` to pass a label to the `<Checkbox>` component. Would you want me to aggregate all "messages" from results with a status of "skip" and pass that to the `<Checkbox>` component? Should we expect multiple "skip" results for a single step?

2021-02-18 23:16 UTC, davisagli commented on src/js/components/plans/detail.tsx
> +        }
@Br4nd0R ah ok, I kinda thought it must be something like that but I wasn't spotting where the `skipped` result object was used. It's theoretically possible that there could be multiple checks which each set a status of `skip` with a different message -- but it's enough of an edge case that I'm fine calling that out of scope for this particular change and only show the first one.

2021-02-19 15:11 UTC, davisagli commented
@Br4nd0R super close but frontend coverage is no longer at 100%

2021-02-22 16:46 UTC, davisagli approved these changes

2021-02-22 17:05 UTC, merged