Gracefully handle ip restriction errors when logging in
SFDO-Tooling/MetaDeploy pull request #2341
Opened 2021-02-12 16:29 UTC by Br4nd0R

# Changes
* MetaDeploy now has `custom_500_view` which defaults to displaying a generic error message. If the view detects that an error was raised in regards to ip restrictions, then we inform the user that ip restriction appear to be in place for the org they're logging into.

2021-02-12 16:53 UTC, davisagli requested changes

2021-02-12 16:53 UTC, davisagli commented on metadeploy/tests/views.py
> +    request = RequestFactory().get("path")
What's this for?

2021-02-12 16:53 UTC, davisagli commented on metadeploy/views.py
> +            "We've detected that your org has ip login recstrictions in place. "
typo

2021-02-12 16:53 UTC, davisagli commented on metadeploy/views.py
> +            "We've detected that your org has ip login recstrictions in place. "
I think the actual name of the feature is Login IP Ranges https://developer.salesforce.com/docs/atlas.en-us.securityImplGuide.meta/securityImplGuide/users_profiles_epui_login_ip_ranges_edit.htm

2021-02-12 16:53 UTC, davisagli commented on metadeploy/views.py
> +            "We've detected that your org has ip login recstrictions in place. "
Also it'd be more accurate to say user rather than org. Login IP Ranges are added to a profile, and different users can have different profiles

2021-02-12 16:53 UTC, davisagli commented on metadeploy/views.py
> +            "Please whitelist the IP addresses listed in the plan's description."
What if they haven't been added to the plan description? I'm not sure we can provide generic instructions for how to resolve this for all instances of metadeploy.

2021-02-12 16:53 UTC, davisagli commented on metadeploy/views.py
> +    message = GENERIC_ERROR_MSG
Have you confirmed that the actual error message still gets logged? I suspect it does, but we don't want the nicer error view to get in the way of us being able to look up what happened, so worth double checking.

2021-02-12 18:41 UTC, Br4nd0R commented on metadeploy/tests/views.py
> +    request = RequestFactory().get("path")
RequestFactory() returns a factory object, not an actual request. So these tests weren't setup properly by me in the first place.

2021-02-12 18:42 UTC, Br4nd0R commented on metadeploy/views.py
> +            "Please whitelist the IP addresses listed in the plan's description."
fixed with a new setting so we can list IPs to whitelist in a config var.

2021-02-12 18:45 UTC, Br4nd0R commented on metadeploy/views.py
> +    message = GENERIC_ERROR_MSG
Confirmed that the error message raised is still found in the app logs (along with the stacktrace).

2021-02-12 18:51 UTC, davisagli commented on metadeploy/tests/views.py
> +    request = RequestFactory().get("path")
Oh yeah, I see.

2021-02-12 18:53 UTC, davisagli commented on metadeploy/views.py
> +            "Please whitelist the IP addresses listed in the plan's description."
@Br4nd0R oh, that's a good idea. But we should only include the sentence that references IPS_TO_WHITELIST if it has actually been configured.

2021-02-12 19:00 UTC, davisagli commented on metadeploy/views.py
> +            "Please whitelist the IP addresses listed in the plan's description."
@Br4nd0R and it should be allowlist, not whitelist

2021-02-12 20:40 UTC, Br4nd0R commented on metadeploy/views.py
> +            "Please whitelist the IP addresses listed in the plan's description."
@davisagli - Are you saying the at the message should say, "Please allowlist the IP addressess..." or that the `IPS_TO_WHITELIST` var should be `IPS_TO_ALLOWLIST`?

2021-02-12 20:46 UTC, davisagli commented on metadeploy/views.py
> +            "Please whitelist the IP addresses listed in the plan's description."
@Br4nd0R we should not use "whitelist" anywhere; it's non-inclusive language.

I think the message should say "Unable to access this org because your user has IP Login Ranges that block access." and if IPS_TO_ALLOWLIST is set, add "Please ensure that the following IP addresses are included in the IP Login Ranges for your user's Profile:"

2021-02-17 15:50 UTC, davisagli commented on metadeploy/views.py
> +            )
@Br4nd0R Now I'm thinking we should make the entire IP_RESTRICTED_MSG configurable in a setting (and take out IPS_TO_ALLOWLIST). It'll keep things flexible if a particular instance wants to use different wording. Default would be "Unable to access this org because your user has IP Login Ranges that block access." like you have above.

2021-02-17 16:41 UTC, davisagli approved these changes

2021-02-17 16:52 UTC, merged