📦 🐈 dependency updates
SFDO-Tooling/MetaDeploy pull request #2674
Opened 2021-04-29 15:32 UTC by Br4nd0R

2021-04-29 20:36 UTC, davisagli requested changes

2021-04-29 20:36 UTC, davisagli commented on package.json
> +    "@testing-library/jest-dom": "^5.12.0",
There are some errors from jest in the "lint" build.

2021-04-29 20:36 UTC, davisagli commented on requirements/test.txt
> +black==21.4b1
Need to make sure we've run the new version on existing files.

2021-04-30 15:31 UTC, Br4nd0R commented on package.json
> +    "@testing-library/jest-dom": "^5.12.0",
@davisagli - I tried playing around to fix this error which is popping up in the tests but I'm not sure of how to change the syntax based on what `eslint-plugin-jest` shows for [this particular error](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-conditional-expect.md).

The `expect()` calls can't be in the call to `catch()` because `catch()` only executes conditionally (if there is a rejected case for the promise). Not sure how to shift things around to have `expect()` calls not in the `catch()` method. 

If you can show me an example of how to do it for one, I can fix the rest of them.

2021-04-30 20:04 UTC, davisagli commented on package.json
> +    "@testing-library/jest-dom": "^5.12.0",
@Br4nd0R It's a lint warning (about a situation that could lead to silently skipping test assertions) rather than a hard failure, so I just disabled the lint rule.

2021-04-30 20:04 UTC, davisagli approved these changes

2021-04-30 20:46 UTC, merged