Cron Job for calculating average plan duration
SFDO-Tooling/MetaDeploy pull request #3028
Opened 2021-08-04 20:24 UTC by Br4nd0R

2021-08-05 14:54 UTC, davisagli requested changes
Mostly looks good so far but I think we can avoid needing to change the frontend.

2021-08-05 14:54 UTC, davisagli commented on config/settings/base.py
> +        "cron_string": "0 0 * * *" # run dialy at midnight
```suggestion
        "cron_string": "0 0 * * *" # run daily at midnight
```

2021-08-05 14:54 UTC, davisagli commented on metadeploy/api/models.py
> +        help_text="The duration between the enqueing of a job and its successful completion."
```suggestion
        help_text="The duration between the enqueueing of a job and its successful completion."
```

2021-08-05 14:54 UTC, davisagli commented on src/js/store/plans/reducer.ts
> +  calculated_average_duration: string | null;
Rather than changing the name that is serialized, I think you want to change `average_duration` on the PlanSerializer to be a SerializerMethodField so that you can implement the logic for reading it as a method instead of getting it directly from the field with the same name.

2021-08-05 16:53 UTC, Br4nd0R commented on metadeploy/adminapi/tests/api.py
> +                    "calculated_average_duration": None,
@davisagli - I'm trying to figure out why these were needed. The `PlanViewSet` specifies the `PlanSerializer` as the serializer class. That serializer doesn't reference calculated_average_duration at all, so why is this field showing in these view sets?

2021-08-05 18:10 UTC, davisagli commented on metadeploy/adminapi/tests/api.py
> +                    "calculated_average_duration": None,
@Br4nd0R This took me a second to figure out. The PlanSerializer in metadeploy/api/serializers.py specifies `fields` and only includes those fields. But this is a test for the admin API which uses a different PlanSerializer in https://github.com/SFDO-Tooling/MetaDeploy/blob/2b2f222dc82e43f6d233136837f9b0e23ed672c3/metadeploy/adminapi/api.py, and that one includes all fields. You can add `exclude` there if we don't want it https://www.django-rest-framework.org/api-guide/serializers/#specifying-which-fields-to-include

2021-08-05 20:59 UTC, Br4nd0R commented on metadeploy/adminapi/tests/api.py
> +                    "calculated_average_duration": None,
We can leave it in; I don't think it's hurting anything.

2021-08-05 21:08 UTC, davisagli commented on metadeploy/adminapi/tests/api.py
> +                    "calculated_average_duration": None,
@Br4nd0R it does mean clients of the admin API can write a value to this field, which feels a bit wrong.

2021-08-06 14:30 UTC, davisagli commented on metadeploy/api/migrations/0114_plan_calculated_average_duration.py
> +                verbose_name="Average duration of a plan (seconds)",
I just noticed that we're calling it the average but calculating it as the median (which is what we want)

2021-08-06 14:31 UTC, davisagli requested changes

2021-08-06 14:31 UTC, davisagli commented on metadeploy/api/serializers.py
> +        return obj.calculated_average_duration or obj.average_duration
```suggestion
        return obj.calculated_average_duration
```

so that we don't always try to recalculate when calculated_average_duration is None because not enough jobs have run yet

2021-08-06 16:21 UTC, davisagli approved these changes

2021-08-06 16:24 UTC, merged