Assistive Text update for progress indicator
SFDO-Tooling/MetaDeploy pull request #3428
Opened 2022-06-09 23:55 UTC by davidjray

Move the SLDS assistive text to the element designated as the label. This acts as a dynamic progress indicator, and gives users a better experience.

2022-06-10 22:10 UTC, bethbrains requested changes

2022-06-10 22:10 UTC, bethbrains commented on src/js/components/jobs/progressBar.tsx
> +                {t('{{percent}}% Complete', { percent: progressRounded })}
does this need to be added to the translation file?

2022-06-10 23:43 UTC, davidjray commented on src/js/components/jobs/progressBar.tsx
> +                {t('{{percent}}% Complete', { percent: progressRounded })}
@bethbrains nope! it's already included 👍🏽

2022-06-13 22:07 UTC, bethbrains approved these changes

2022-06-13 23:15 UTC, merged