Working /api/userinfo/ endpoint without tests
SFDO-Tooling/MetaDeploy pull request #3465
Opened 2022-09-30 14:59 UTC by jofsky

2022-10-02 23:22 UTC, jofsky commented
Let's make sure we squash on this merge.

2022-10-03 18:45 UTC, TheBitShepherd requested changes

2022-10-03 18:45 UTC, TheBitShepherd commented on metadeploy/api/views.py
> +    This is an endpoint to show the user id of the current user.
```suggestion
    If authenticated, returns the current user's username.
```

2022-10-03 18:45 UTC, TheBitShepherd commented on metadeploy/api/views.py
> +
```suggestion
            return Response({"username": self.request.user.username})
```

2022-10-04 18:31 UTC, TheBitShepherd approved these changes

2022-10-04 18:59 UTC, merged